### ISSUE TITLE
AttributeError: module 'tmap' has no attribute 'layout_from_edge_list'

### ISSUE THREAD

**Issue by dohalloran** [reymond-group/tmap#12]
Getting the following error when running the [simple graph](https://tmap.gdb.tools/#simple-graph)
`AttributeError: module 'tmap' has no attribute 'layout_from_edge_list'`

**Comment by lfnothias** [comment]
I had a similar issue when installing the tmap package from the conda-forge channel instead of the tmap channel.
If that the same reason here, the solution is to the install as recommend : `conda install -c tmap tmap`

**Comment by dohalloran** [comment]
that's exactly how i installed it using `conda install -c tmap tmap` but get that error for `layout_from_edge_list`

**Comment by aparente-nurix** [comment]
When I’ve had issues installing/Conda being behind on bug fixes I just installed from github. Clone the repo and use Conda develop (part of the Conda-build package) to add the repo path to your environments Conda path.

________________________________

**Comment by lfnothias** [comment]
Installing with `conda install -c tmap tmap` worked for me, and I was able to run the example code for `layout_from_edge_list`. See https://github.com/reymond-group/tmap/issues/11

**Comment by Lerbytech** [comment]
Interesting.... I had to rebuild tmap from scratch as conda version throwed "Wrong cpu instucrion" to consle for test examples. So, pip version is working? Cool.

**Comment by aparente-nurix** [comment]
I haven't tried pip. The latest conda build works for me on centos 7. In the past when I had issues I downloaded the repo and used:

conda develop path_to_repo

**Comment by Lerbytech** [comment]
Oh, i was wrong. Not pip but conda package. Also, I have Ubuntu, not CentOS if it may be important. Anyway - for future generations. If you have problems with package - rebuilding it can help. I did it by recreating steps from `https://github.com/reymond-group/tmap/blob/master/azure-pipelines.yml`

**Comment by dohalloran** [comment]
turns out the issue I was having was only on MAC OS, and it worked fine on Linux
