### ISSUE TITLE
What is the license of tmap?

### ISSUE THREAD

**Issue by rahulavadhoot** [reymond-group/tmap#2]
I'm unable to find the license of tmap

**Comment by hadim** [comment]
@daenuprobst can you clarify about the license?

**Comment by kellpossible** [comment]
MIT perhaps? https://github.com/reymond-group/tmap/blob/9aa043dd1af022161048ee0a4b5554ec5e34977f/tmap/recipe/meta.yaml#L45

**Comment by doublethefish** [comment]
It looks like the _intent_ is for the license to be MIT, but because it statically links in ODGF (LDPL) it is actually an LGPL license. So, buyer beware.

**Comment by doublethefish** [comment]
Fixed by https://github.com/reymond-group/tmap/pull/29
