### ISSUE TITLE
Map is missing São Tomé and Príncipe

### ISSUE THREAD

**Issue by rskl92** [reymond-group/tmap#37]
Hello,

I am trying to highlight different countries on the world map using tmap and I noticed that São Tomé and Príncipe in Africa is not listed. How can I add this so I can work on my project?

Many thanks

**Comment by doublethefish** [comment]
Hey thanks for the question. Without more information we can’t help you. Feel free to add more descriptive information about how we can see the same issue you’re seeing and we’ll try and help - it sounds like you just need to as some data somewhere but without more details we can’t tell where or how.

Closing for now.
