### ISSUE TITLE
What if I have a distance matrix (Gram matrix)?

### ISSUE THREAD

**Issue by UnixJunkie** [reymond-group/tmap#38]
Hello,
It would be nice if you can work from that.
I.e. what I want to map are not molecules, but I have the full distance matrix
for the dataset.
Regards,
F.

**Comment by UnixJunkie** [comment]
I.e. we can probably skip the kNN pass.

**Comment by doublethefish** [comment]
Your request isn't very clear. Please elaborate with more details and re-open.

**Comment by UnixJunkie** [comment]
It would be nice if we can use this package using a distance matrix as input.
I.e. we have already calculated the all to all distances for the dataset at hand.

**Comment by UnixJunkie** [comment]
I am not allowed to reopen this issue though...
